### PR TITLE
Added Tampermonkey Download Parameter (YouTube)

### PR DESCRIPTION
**Pull request by TheAlienDrew**
This allows Tampermonkey to check for updates, and auto update the app directly after changes are made to the GitHub repo.

### CODE REVIEW

**Comment by maple3142** [comment]
I think userscript manager should already be able to fetch updates from original installtional url, at least ViolentMonkey does this.

**Comment by TheAlienDrew** [comment]
Well, sadly, tampermonkey requires there to be a URL to update.

**Comment by maple3142** [comment]
Then that it their problem, and I shouldn't need to add that.

**Comment by TheAlienDrew** [comment]
What's wrong with adding a downloadURL line for more userscript compatibility?

**Comment by maple3142** [comment]
Because it is not necessary.

**Pull request closed without merging**
